### ISSUE TITLE
Did I install the program properly?

### ISSUE THREAD

**Issue by vvlaw** [retrontology/sup2srt#13]
vvlaw@archlinux  ~/sup2srt/build   main  make -j ${nproc}                                                                                            ✔  7295  21:30:38
[  5%] Building CXX object src/CMakeFiles/sup2disk.dir/sup2disk.cpp.o
[ 10%] Building CXX object src/CMakeFiles/sup2disk.dir/mkvUtil.cpp.o
[ 15%] Building CXX object src/pgs/CMakeFiles/pgs.dir/displaySegment.cpp.o
[ 20%] Building CXX object src/pgs/CMakeFiles/pgs.dir/objectDefinitionSegment.cpp.o
[ 25%] Building CXX object src/pgs/CMakeFiles/pgs.dir/compositionObject.cpp.o
[ 30%] Building CXX object src/pgs/CMakeFiles/pgs.dir/paletteSegment.cpp.o
[ 35%] Building CXX object src/pgs/CMakeFiles/pgs.dir/pgsParser.cpp.o
[ 40%] Building CXX object src/pgs/CMakeFiles/pgs.dir/paletteDefinitionSegment.cpp.o
[ 45%] Building CXX object src/pgs/CMakeFiles/pgs.dir/pgsSegment.cpp.o
[ 50%] Building CXX object src/pgs/CMakeFiles/pgs.dir/pgsSegmentHeader.cpp.o
[ 55%] Building CXX object src/pgs/CMakeFiles/pgs.dir/presentationCompositionSegment.cpp.o
[ 60%] Building CXX object src/pgs/CMakeFiles/pgs.dir/pgsUtil.cpp.o
[ 65%] Building CXX object src/pgs/CMakeFiles/pgs.dir/windowDefinitionSegment.cpp.o
[ 70%] Building CXX object src/pgs/CMakeFiles/pgs.dir/windowSegment.cpp.o
[ 75%] Linking CXX executable sup2disk
[ 80%] Linking CXX static library libpgs.a
[ 80%] Built target pgs
[ 95%] Building CXX object src/CMakeFiles/sup2srt.dir/sup2srt.cpp.o
[ 95%] Building CXX object src/CMakeFiles/sup2srt.dir/srtUtil.cpp.o
[ 95%] Building CXX object src/CMakeFiles/sup2srt.dir/mkvUtil.cpp.o
[ 95%] Built target sup2disk
[100%] Linking CXX executable sup2srt
[100%] Built target sup2srt
 vvlaw@archlinux  ~/sup2srt/build   main  sup2srt                                                                                                     ✔  7296  21:30:59
zsh: command not found: sup2srt

**Comment by retrontology** [comment]
It looks like you built it correctly. It looks like it is just not installed to a directory in your path. I did just notice that I happened to omit that step in the documentation. Sorry about that :sweat_smile: 

In order to install it to a directory in your path and be able to call without using the absolute path, you have to run the following command after you build it:
```
sudo make install
```
After you do that, you should be able to use sup2srt from any directory. Let me know if that doesn't work for you because there is one other thing I can think it might be.

**Comment by retrontology** [comment]
Going to close this out. If you still need assistance @vvlaw, please reopen this issue
